---
name: portal-ui                                      # 서비스 배포이름(필수) bosh deployments 로 확인 가능한 이름

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

releases:
- name: paasta-portal-ui-release                          # 서비스 릴리즈 이름(필수) bosh releases로 확인 가능
  url: http://45.248.73.44/index.php/s/FqygsF7pE3DS7Cf/download
  version: "2.2.0"                                         # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

update:
  canaries: 1                                               # canary 인스턴스 수(필수)
  canary_watch_time: 5000-120000                            # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  update_watch_time: 5000-120000                            # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 1                                          # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  serial: false

instance_groups:
########## INFRA ##########
- name: mariadb
  azs: ((mariadb_azs))
  instances: ((mariadb_instances))
  vm_type: ((mariadb_vm_type))
  stemcell: default
  persistent_disk_type: ((mariadb_persistent_disk_type))
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mariadb
    release: paasta-portal-ui-release
  syslog_aggregator: null

- name: haproxy
  azs: ((haproxy_azs))
  instances: ((haproxy_instances))
  vm_type: ((haproxy_vm_type))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  - name: ((public_networks_name))
    static_ips: ((haproxy_public_ips))
  jobs:
  - name: haproxy
    release: paasta-portal-ui-release
  syslog_aggregator: null
  properties:
    infra:
      admin:
        enable: ((haproxy_infra_admin))

######## WEB SERVICE ########

- name: paas-ta-portal-webadmin
  azs: ((webadmin_azs))
  instances: ((webadmin_instances))
  vm_type: ((webadmin_vm_type))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: paas-ta-portal-webadmin
    release: paasta-portal-ui-release
  syslog_aggregator: null
  properties:
    java_opts: "-Xmx450m -Xss1M -XX:MaxMetaspaceSize=93382K -XX:ReservedCodeCacheSize=240m -XX:+UseCompressedOops -Djdk.tls.ephemeralDHKeySize=2048 -Dfile.encoding=UTF-8 -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -XX:+HeapDumpOnOutOfMemoryError -XX:-OmitStackTraceInFastThrow -Xverify:none -XX:ErrorFile=/var/vcap/sys/log/java_error_in_idea_%p.log -XX:HeapDumpPath=/var/vcap/sys/log/java_error_in_idea.hprof"
    api:
      url: "((portal_default_api_url))"
    port: 8090

- name: paas-ta-portal-webuser
  azs: ((webuser_azs))
  instances: ((webuser_instances))
  vm_type: ((webuser_vm_type))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: paas-ta-portal-webuser
    release: paasta-portal-ui-release
  syslog_aggregator: null
  properties:
    logPath: "/var/vcap/sys/log/paas-ta-portal-webuser"     # WEBUSER는 아파치를 사용함, APACHE 로그 위치
    webDir: "/var/vcap/packages/apache2/htdocs"             # WEBUSER는 아파치를 사용함, APACHE 웹 디렉토리 설정
    cf:
      uaa:
        clientsecret: ((uaa_client_portal_secret))
    monitoring: ((webuser_monitoring))
    quantity: ((webuser_quantity))
    automaticApproval: ((webuser_automaticapproval))

properties:
  mariadb:                                                  # MARIA DB SERVER 설정 정보
    port: ((mariadb_port))                                  # MARIA DB PORT 번호
    admin_user:
      password: ((mariadb_admin_password))                 # MARIA DB ROOT 계정 비밀번호
    host_names:
    - mariadb0
  portal_default:
    name: "((portal_default_api_name))"
    url: "((portal_default_api_url))"
    uaa_url: "https://uaa.((system_domain))"
    header_auth: "((portal_default_header_auth))"
    desc: "((portal_default_api_desc))"
  cf_api_version: ((paasta_api_version))
  webadmin_ips: ((haproxy_public_ips))
